Netflix:
  outputs:
    default: 
      type: snowflake
      account: <account-name>
      user: <user-name>
      password: <snowflake-password>
      role: ACCOUNTADMIN
      database: <Database-Name>
      warehouse: COMPUTE_WH
      schema: DBT_RAW
    dev:
      type: snowflake
      account: <account-name>
      user: <user-name>
      password: <snowflake-password>
      role: ACCOUNTADMIN
      database: <Database-Name>
      warehouse: COMPUTE_WH
      schema: DBT_TRANSFORM
    prod:
      type: snowflake
      account: <account-name>
      user: <user-name>
      password: <snowflake-password>
      role: ACCOUNTADMIN
      database: <Database-Name>
      warehouse: COMPUTE_WH
      schema: DBT_PROD

